services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    env_file:
      - mysql.env
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - twotier
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uadmin", "-padmin"]
      interval: 10s
      retries: 5
      start_period: 60s
      timeout: 5s

  flaskapp:
    build:
      context: .
    container_name: flaskapp
    env_file:
      - flask.env
    networks:
      - twotier
    ports:
      - "80:5000"
    depends_on:
      mysql:
        condition: service_healthy
    restart: always

volumes:
  mysql-data:
networks:
  twotier:
